export const types = {
  SET_POST_COMMENTS: 'SET_POST_COMMENTS',
  GET_POST_COMMENTS: 'GET_POST_COMMENTS',
  INIT_LOADING_COMMENTS: 'INIT_LOADING_COMMENTS',
  SET_ERROR_COMMENT: 'SET_ERROR_COMMENT',
  CLEAN_COMMENTS: 'CLEAN_COMMENTS',
}